export default function PrivacyPage() {
  return (
    <div className="pt-16 bg-white">
      <div className="max-w-5xl mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold text-center mb-4">Privacy Policy</h1>
        <p className="text-sm text-gray-500 text-center mb-12">
          Last updated: January 23, 2025
        </p>

        <div className="space-y-8">
          <div>
            <p className="text-base text-gray-700 leading-relaxed space-y-4">
              This Privacy Policy outlines the practices and principles
              regarding the collection, use, and disclosure of your information
              when you use our service. It aims to inform you about your privacy
              rights and the legal protections afforded to you. We are committed
              to safeguarding your privacy and ensuring the security of your
              information in accordance with applicable laws and regulations. By
              using our service, you acknowledge and consent to the collection,
              use, and disclosure of your information as described in this
              Privacy Policy. We encourage you to read this policy carefully and
              contact us if you have any questions or concerns at{" "}
              <a
                href="mailto:info@maxpark.in"
                className="text-blue-600 hover:underline"
              >
                info@maxpark.in
              </a>
              . Your privacy is important to us, and we are dedicated to
              protecting and respecting your personal information.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mt-4">
              This Privacy Policy has been created with the help of the Terms
              Feed Privacy Policy Generator.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              1. Interpretation and Definitions
            </h2>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Interpretation
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or plural.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Definitions
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              For the purposes of this Privacy Policy:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base text-gray-700 leading-relaxed">
              <li>
                <strong>Account</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Application</strong> refers to Maxpark, the software
                program provided by the Company.
              </li>
              <li>
                <strong>Company</strong> (referred to as either "the Company",
                "We", "Us", or "Our" in this Agreement) refers to Maxpark
                Solutions Private Limited, HYDERABAD.
              </li>
              <li>
                <strong>Country</strong> refers to Telangana, India
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone, or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Application.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal
                person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the
                Company to facilitate the Service, to provide the Service on
                behalf of the Company, to perform services related to the
                Service, or to assist the Company in analyzing how the Service
                is used.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit).
              </li>
              <li>
                <strong>You</strong> mean the individual accessing or using the
                Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>
            <p className="text-base text-gray-700 leading-relaxed mt-4">
              At Maxpark, we employ various methods to collect and receive
              personal information through our Site. We strive to ensure that
              you have control over the information you provide, although there
              are instances where certain information is necessary to access and
              utilize the full features of the Site.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              2. Data Collection
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Maxpark collects user information necessary for account
              registration and platform usage. This may include:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base text-gray-700 leading-relaxed mb-4">
              <li>
                personal details such as your name, gender, age, location &
                profile photo
              </li>
              <li>vehicle details such as vehicle number</li>
            </ul>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              The collected data is used to enhance user experience, provide
              personalized content, and improve our services. We do not share or
              sell user data to third parties without explicit consent.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              It is vital that you provide accurate and complete personal
              information. Failure to do so may result in delays in accessing
              requested products and services.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Data Collected Automatically Through Your Use of the Site:
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              While using Our Application, in order to provide features of Our
              Application, We may collect, with Your prior permission:
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              <strong>Geolocation Data:</strong> With your consent, we may
              collect precise geolocation Latitude and Longitude data from your
              mobile device. This information enables us to provide relevant
              services and improve user experience. It's important to note that
              certain features may not function properly if you do not consent
              to sharing geolocation data.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              The automatically collected information assists us in
              understanding our visitors, their preferences, and their origins,
              allowing us to enhance the quality and relevance of our Site.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              You can enable or disable access to this information at any time
              through Your Device settings.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Usage Data:
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Usage Data may include information such as Your Device's Internet
              Protocol address (e.g., IP address), browser type, browser
              version, the pages of our Service that You visit, the time and
              date of Your visit, the time spent on those pages, unique device
              identifiers, and other diagnostic data.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              When You access the Service by or through a mobile device, We may
              collect certain information automatically, including, but not
              limited to, the type of mobile device You use, Your mobile
              device's unique ID, the IP address of Your mobile device, Your
              mobile operating system, the type of mobile Internet browser You
              use, unique device identifiers, and other diagnostic data.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              We may also collect information that Your browser sends whenever
              You visit our Service or when You access the Service by or through
              a mobile device.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              3. How we use the collected Data
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base text-gray-700 leading-relaxed mb-4">
              <li>
                To provide and maintain our Service, including monitoring the
                usage of our Service.
              </li>
              <li>
                To manage Your Account: to manage Your registration as a user of
                the Service. The Personal Data You provide can give You access
                to different functionalities of the Service that are available
                to You as a registered user.
              </li>
              <li>
                For the performance of a contract: the development, compliance,
                and undertaking of the purchase contract for the products,
                items, or services You have purchased or of any other contract
                with Us through the Service.
              </li>
              <li>
                To contact You: To contact You by email, telephone calls, SMS,
                or other equivalent forms of electronic communication, such as a
                mobile application's push notifications regarding updates or
                informative communications related to the functionalities,
                products, or contracted services, including security updates
                when necessary or reasonable for their implementation.
              </li>
              <li>
                To provide You with news, special offers, and general
                information about other goods, services, and events which we
                offer that are similar to those that you have already purchased
                or enquired about unless You have opted not to receive such
                information.
              </li>
              <li>
                For other purposes: We may use Your information for other
                purposes, such as data analysis, identifying usage trends,
                determining the effectiveness of our promotional campaigns, and
                evaluating and improving our Service, products, services,
                marketing, and your experience.
              </li>
            </ul>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              We may also share Your personal information in the following
              situations:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base text-gray-700 leading-relaxed">
              <li>
                <strong>For business transfers:</strong> We may share or
                transfer Your personal information in connection with, or during
                negotiations of, any merger, sale of Company assets, financing,
                or acquisition of all or a portion of Our business to another
                company.
              </li>
              <li>
                <strong>With Affiliates:</strong> We may share Your information
                with Our affiliates, in which case, we will require those
                affiliates to honour this Privacy Policy. Affiliates include Our
                parent company and any other subsidiaries, joint venture
                partners, or other companies that We control or that are under
                common control with Us.
              </li>
              <li>
                <strong>With Your consent:</strong> We may disclose Your
                personal information for any other purpose with Your consent.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              4. Retention of Your Personal Data
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use Your Personal Data to the extent necessary to
              comply with our legal obligations (for example, if we are required
              to retain your data to comply with applicable laws), resolve
              disputes, and enforce our legal agreements and policies.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              The Company will also retain Usage Data for internal analysis
              purposes. Usage Data is generally retained for a shorter period of
              time, except when this data is used to strengthen the security or
              to improve the functionality of Our Service, or We are legally
              obligated to retain this data for longer time periods.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              5. Transfer of Your Personal Data
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Your information, including Personal Data, is processed at the
              Company's operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to and maintained on computers
              located outside of Your state, province, country, or other
              governmental jurisdiction where the data protection laws may
              differ from those of Your jurisdiction.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Your consent to this Privacy Policy, followed by Your submission
              of such information, represents Your agreement to that transfer.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              The Company will take all steps reasonably necessary to ensure
              that Your data is treated securely and in accordance with this
              Privacy Policy. No transfer of Your Personal Data will take place
              to an organization or a country unless there are adequate controls
              in place, including the security of Your data and other personal
              information.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              6. Delete Your Personal Data
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              You have the right to delete or request that We assist in deleting
              the Personal Data that We have collected about You.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Our Service may give You the ability to delete certain information
              about You from within the Service.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              You may update, amend, or delete Your information at any time by
              signing in to Your Account if you have one, and visiting the
              account settings section that allows you to manage Your personal
              information. You may also contact Us to request access to,
              correct, or delete any personal information that You have provided
              to Us.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              Please note, however, that We may need to retain certain
              information when we have a legal obligation or lawful basis to do
              so.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              7. Disclosure of Your Personal Data
            </h2>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Business Transactions
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              If the Company is involved in a merger, acquisition, or asset
              sale, Your Personal Data may be transferred. We will provide
              notice before Your Personal Data is transferred and becomes
              subject to a different Privacy Policy.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Law enforcement
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Under certain circumstances, the Company may be required to
              disclose Your Personal Data if required to do so by law or in
              response to valid requests by public authorities (e.g., a court or
              a government agency).
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Other legal requirements
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              The Company may disclose Your Personal Data in good faith belief
              that such action is necessary to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base text-gray-700 leading-relaxed">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>
                Prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                Protect the personal safety of Users of the Service or the
                public
              </li>
              <li>Protect against legal liability</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              8. Security of Your Personal Data
            </h2>
            <p className="text-base text-gray-700 leading-relaxed">
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              9. Children's Privacy
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Our Service does not address anyone under the age of 13. We do not
              knowingly collect personally identifiable information from anyone
              under the age of 13. If You are a parent or guardian and You are
              aware that Your child has provided Us with Personal Data, please
              contact Us. If We become aware that We have collected Personal
              Data from anyone under the age of 13 without verification of
              parental consent, We take steps to remove that information from
              Our servers.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              If We need to rely on consent as a legal basis for processing Your
              information and Your country requires consent from a parent, We
              may require Your parent's consent before We collect and use that
              information.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              10. Links to Other Websites
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third-party link, You will be
              directed to that third-party's site. We strongly advise You to
              review the Privacy Policy of every site You visit.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              We have no control over and assume no responsibility for the
              content, privacy policies, or practices of any third-party sites
              or services.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              11. Changes to this Privacy Policy
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              We will let You know via email and/or a prominent notice on Our
              Service, prior to the change becoming effective and update the
              "Last updated" date at the top of this Privacy Policy.
            </p>
            <p className="text-base text-gray-700 leading-relaxed">
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-4 mt-10">
              12. GDPR Compliance
            </h2>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              At Maxpark, we are committed to ensuring compliance with the
              General Data Protection Regulation (GDPR) and the protection of
              the rights and privacy of our users.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Lawful Basis for Processing
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              We will only process personal data when we have a lawful basis to
              do so. This may include obtaining explicit consent from
              individuals or processing personal data for the performance of a
              contract.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Data Subject Rights
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              Under GDPR, individuals have certain rights regarding their
              personal data. These rights include the right to access, rectify,
              erase, restrict processing, and object to the processing of their
              personal data. Individuals also have the right to data
              portability.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Data Security
            </h3>
            <p className="text-base text-gray-700 leading-relaxed mb-4">
              We implement appropriate technical and organizational measures to
              ensure the security and confidentiality of personal data. This
              includes measures to prevent unauthorized access, loss,
              disclosure, or alteration of personal data.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Data Breach Notification
            </h3>
            <p className="text-base text-gray-700 leading-relaxed">
              In the event of a data breach that is likely to result in a risk
              to individuals' rights and freedoms, we will notify the relevant
              supervisory authority and affected individuals without undue
              delay.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
